version: '2'
services:
  couchdb:
    image: klaemo/couchdb
  prefserver:
    image: gpiilab/preferences-server
    ports:
      - 8081:8081
    links:
      - couchdb
    depends_on:
      - couchdb      
  dataloader:
    image: gpiilab/dataloader
    links:
      - couchdb
    depends_on:
      - couchdb
      - prefserver
