apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gpii-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gpii
    spec:

      containers:
      - name: couchdb
        image: klaemo/couchdb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5984
      - name: preferences-server
        image: gpiilab/preferences-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
      - name: flow-manager
        image: gpiilab/flow-manager
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
